// Client/src/components/LoginComponent.tsx
// LoginPage.tsx
import React, { useState } from "react";
import useCountDown from "../hooks/useCountDown";
import type { HandyLoginModel, LoginPageProps } from "../types/LoginTypes";
import "./LoginComponent.css";

const LoginPage: React.FC<LoginPageProps> = ({
  cooldownSeconds = 5,
  maxAttempts = 5,
  noticeText = "",
  // redirectLink = "/",
  loginCallback,
}) => {
  const [model, setModel] = useState<HandyLoginModel>({
    email: "",
    password: "",
    rememberMe: false,
  });
  const [isPasswordVisible, setIsPasswordVisible] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errMsg, setErrMsg] = useState("");
  const [attemptsNotice, setAttemptsNotice] = useState("");
  const [attempts, setAttempts] = useState(0);
  const [isCoolingDown, setIsCoolingDown] = useState(false);

  const { secondsLeft, startTimer } = useCountDown({
    onComplete: () => {
      // console.log("time is up");
      setIsCoolingDown(false);
      setAttempts(0);
      setErrMsg("");
      setAttemptsNotice("");
    },
    onTick: () => {
      setErrMsg(
        `Too many attempts. Please wait ${secondsLeft} seconds before trying again.`
      );
    },
  });

  const togglePasswordVisibility = () => setIsPasswordVisible((prev) => !prev);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value, checked, type } = e.target;
    // console.log(id, value, checked, type);
    setModel((prev) => ({
      ...prev,
      [id]: type === "checkbox" ? checked : value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isCoolingDown) return;

    setLoading(true);
    setErrMsg("");
    setAttemptsNotice("");
    setAttempts((prev) => prev + 1);

    const response = await loginCallback(model);
    setLoading(false);

    if (!response.flag) {
      if (attempts + 1 >= maxAttempts) {
        setIsCoolingDown(true);
        // setErrMsg(cooldownMessage)
        setAttemptsNotice("");

        // start timer here
        startTimer(cooldownSeconds);
      } else {
        setErrMsg(response.message);
        setAttemptsNotice(`${attempts + 1} of ${maxAttempts} attempts`);
      }

      return;
    }

    // TODO: uncomment later when ready
    // window.location.href = redirectLink;
  };

  return (
    <div className="container">
      <form
        id="login_form"
        onSubmit={handleSubmit}
        className="card text-white bg-black"
      >
        <h4 className="card-header">Login</h4>
        <div className="card-body">
          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              type="email"
              className="form-control"
              value={model.email}
              onChange={handleChange}
              required
            />
          </div>
          <div className="form-group mt-3">
            <label htmlFor="password">Password</label>
            <div className="input-group">
              <input
                id="password"
                type={isPasswordVisible ? "text" : "password"}
                className="form-control"
                value={model.password}
                onChange={handleChange}
                required
              />
              <div className="input-group-append">
                <button
                  type="button"
                  className="btn btn-outline-secondary"
                  onClick={togglePasswordVisibility}
                >
                  <i
                    className={`fa ${
                      isPasswordVisible ? "fa-eye" : "fa-eye-slash"
                    }`}
                    aria-hidden="true"
                  ></i>
                </button>
              </div>
            </div>
          </div>

          <div className="form-check my-3">
            <input
              id="rememberMe"
              className="form-check-input"
              type="checkbox"
              checked={model.rememberMe}
              onChange={handleChange}
            />
            <label className="form-check-label" htmlFor="rememberMe">
              Remember Me
            </label>
          </div>

          <button
            className="btn btn-primary"
            type="submit"
            disabled={loading || isCoolingDown}
          >
            {loading && (
              <span className="spinner-border spinner-border-sm mr-1"></span>
            )}{" "}
            Login
          </button>

          {errMsg && <p className="text-danger mt-3">{errMsg}</p>}
          {attemptsNotice && <p className="text-danger">{attemptsNotice}</p>}
        </div>
      </form>

      {noticeText && (
        <div className="text-center font-weight-bold mt-3">{noticeText}</div>
      )}
    </div>
  );
};

export default LoginPage;

// Client/src/components/LoginComponent.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import useCountDown from '../composables/useCountDown';
import type { LoginModel, LoginPageProps } from "../types/LoginTypes";

const { cooldownSeconds, maxAttempts, noticeText, redirectLink, onLogin } = withDefaults(defineProps<LoginPageProps>(), {
  cooldownSeconds: 10,
  maxAttempts: 5,
  noticeText: "",
  redirectLink: "/",
});

const model = ref<LoginModel>({
  email: "",
  password: "",
  rememberMe: false,
});

const isPasswordVisible = ref(false);
const loading = ref(false);
const errMsg = ref("");
const attemptsNotice = ref("");
const attempts = ref(0);
const isCoolingDown = ref(false);
const router = useRouter();

const { secondsLeft, startTimer } = useCountDown({
  onComplete: () => {
    isCoolingDown.value = false;
    attempts.value = 0;
    errMsg.value = "";
    attemptsNotice.value = "";
  },
  onTick: () => {
    console.log('tick called!');
    errMsg.value = `Too many attempts. Please wait ${secondsLeft.value} seconds before trying again.`;
  },
});

function togglePasswordVisibility() {
  isPasswordVisible.value = !isPasswordVisible.value;
}

function handleChange(event: Event) {
  const target = event.target as HTMLInputElement;
  const { id, value, checked, type } = target;
  (model.value as any)[id] = type === "checkbox" ? checked : value;

  // console.log(model.value.email);
}

async function handleSubmit() {
  if (isCoolingDown.value) return;
  loading.value = true;
  attempts.value++;

  const response = await onLogin(model.value);
  loading.value = false;

  if (!response.flag) {
    if (attempts.value >= maxAttempts) {
      isCoolingDown.value = true;
      attemptsNotice.value = "";
      startTimer(cooldownSeconds);
    } else {
      errMsg.value = response.message;
      attemptsNotice.value = `${attempts.value} of ${maxAttempts} attempts`;
    }
    return;
  }

  router.push(redirectLink);
}
</script>

<template>
  <div class="container">
    <form id="login_form" @submit.prevent="handleSubmit" class="card text-white bg-black">
      <h4 class="card-header">Login</h4>
      <div class="card-body">
        <div class="form-group">
          <label for="email">Email</label>
          <input
            id="email"
            type="email"
            class="form-control"
            v-model="model.email"
            required
            @input="handleChange"
          />
        </div>
        <div class="form-group mt-3">
          <label for="password">Password</label>
          <div class="input-group">
            <input
              id="password"
              :type="isPasswordVisible ? 'text' : 'password'"
              class="form-control"
              v-model="model.password"
              required
              @input="handleChange"
            />
            <div class="input-group-append">
              <button
                type="button"
                class="btn btn-outline-secondary"
                @click="togglePasswordVisibility"
              >
                <i
                  :class="['fa', isPasswordVisible ? 'fa-eye' : 'fa-eye-slash']"
                  aria-hidden="true"
                ></i>
              </button>
            </div>
          </div>
        </div>

        <div class="form-check my-3">
          <input
            id="rememberMe"
            class="form-check-input"
            type="checkbox"
            v-model="model.rememberMe"
            @change="handleChange"
          />
          <label class="form-check-label" for="rememberMe"> Remember Me </label>
        </div>

        <button
          class="btn btn-primary"
          type="submit"
          :disabled="loading || isCoolingDown"
        >
          <span v-if="loading" class="spinner-border spinner-border-sm mr-1"></span>
          Login
        </button>

        <p v-if="errMsg" class="text-danger mt-3">{{ errMsg }}</p>
        <p v-if="attemptsNotice" class="text-danger">{{ attemptsNotice }}</p>
      </div>
    </form>

    <div v-if="noticeText" class="text-center font-weight-bold mt-3">
      {{ noticeText }}
    </div>
  </div>
</template>

<style scoped>
    /* .container {
    max-width: 400px;
    margin: auto;
    padding-top: 40px;
    } */

    #login_form input {
    color: white;
    background-color: black;
}
</style>
