// Client/src/components/Transactions.tsx
// import React from 'react'

export default function Transactions() {
  return (
    <>
      <div className="text-center mt-5" >
        <h1 className="fw-bold fs-3 mt-5 mb-3">Transactions</h1>
        <div className="d-flex justify-content-center">

          <div className="card bg-dark bg-gradient" /*style={{ width: "25rem"}}*/>
          {/* Card Header */}
          {/* <div className="card-header">
            Total Balance
          </div> */}

          {/* Card Body */}
          <div className="card-body" style={{color: 'white'}}>
            {/* <h5 className="card-title">Total Balance</h5> */}
            <p className="card-text">
              Show all transactions here. Users should be able to sort by filtering for the last week last month, etc. And make list scrollable
            </p>
          </div>

 
          </div>
        </div>

      </div>
    </>
  )
}

// Client/src/components/Transactions.vue
<template>
    <div class="container m-5 p-5">
        <h1 class="fw-bold fs-3 mt-5 mb-3 text-center">Transactions</h1>
        <div class="d-flex justify-content-center">
          <div class="card bg-dark bg-gradient">
            <div class="card-body">
                <h5 class="card-title" style="color: white;">Total Balance</h5>
                <p class="card-text">
                    Show all transactions here. Users should be able to sort by
                    filtering for the last week last month, etc. And make list
                    scrollable
                </p>
            </div>
          </div>
        </div>
    </div>
</template>

<script setup lang="ts">

</script>

<style scoped>
 * {
    color: white;
 }
</style>
